---
title: "p8105_hw6_nkr2121"
author: "Nihaal Rahman"
output: github_document
---

Loading the required packages
```{r, message = FALSE}
library(tidyverse)
```

# Question 2

Reading in the data
```{r, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r message=FALSE, cache=TRUE, warning=FALSE}
set.seed(100)

sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_sample = tibble(num = 1:5000) |> 
  mutate(
    sample = map(num, \(i) sample(weather_df))
  )

results =   
  boot_sample |> 
  mutate(
    models = map(sample, \(df) lm(tmax ~ tmin + prcp, data = df)),
    lm = map(models, broom::tidy),
    glance = map(models, broom::glance)) |> 
  unnest(lm, glance) |> 
  select(num, term, estimate, r.squared) |> 
  pivot_wider(names_from = term, values_from = estimate) |> 
  mutate(log_b_product = log(tmin * abs(prcp)))
```

